"""Deterministic shadow routing for Hermes turns.

This module never invokes a model. It classifies task complexity/risk/privacy
using explicit rules, reads a quality-gated policy generated by the eval
harness, and emits secret-safe JSONL telemetry. In ``shadow`` mode the caller's
provider and model are never changed.
"""

from __future__ import annotations

import hashlib
import hmac
import json
import logging
import os
import re
import secrets
import threading
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


logger = logging.getLogger(__name__)
_PROCESS_FINGERPRINT_KEY = secrets.token_bytes(32)
_WRITE_LOCK = threading.Lock()

_C4_PATTERNS = (
    r"\bdeploy(?:ment)?\b",
    r"\bproduction\b",
    r"\bship\s+(?:it|this|to)\b",
    r"\brollback\b",
    r"\bcanary\b",
    r"\bincident\b",
    r"\bcheckout\b",
    r"\bpayment(?:s)?\b",
    r"\bbilling\b",
    r"\bdelete\s+(?:the\s+)?(?:database|account|records?)\b",
)
_C3_PATTERNS = (
    r"\bsecurity\b",
    r"\bcredential(?:s)?\b",
    r"\bsecret(?:s)?\b",
    r"\bauth(?:entication|orization)?\b",
    r"\blegal\b",
    r"\bmedical\b",
    r"\bfinancial\b",
    r"\btax\b",
    r"\bmigration\b",
    r"\bschema\b",
    r"\binfrastructure\b",
    r"\bdestructive\b",
    r"\bprivacy\b",
    r"\bcompliance\b",
)
_C2_PATTERNS = (
    r"\bplan\b",
    r"\barchitecture\b",
    r"\bimplement\b",
    r"\bdebug\b",
    r"\bcode\b",
    r"\breview\b",
    r"\banaly[sz]e\b",
    r"\bcompare\b",
    r"\bstrategy\b",
    r"\bworkflow\b",
    r"\bmultiple\b",
)
_PRIVATE_PATTERNS = (
    r"\bprivate\b",
    r"\bpersonal\s+data\b",
    r"\bpii\b",
    r"\bcustomer\s+(?:data|record|email|phone|address)\b",
    r"\bpassport\b",
    r"\bsocial\s+insurance\b",
    r"\bhealth\s+record\b",
    r"\bfamily\b",
)


def _matches(text: str, patterns: tuple[str, ...]) -> list[str]:
    return [pattern for pattern in patterns if re.search(pattern, text)]


def classify_task(message: str) -> dict[str, Any]:
    """Return a deterministic C1-C4 classification without retaining content."""
    normalized = " ".join(str(message or "").lower().split())
    private_matches = _matches(normalized, _PRIVATE_PATTERNS)
    c4_matches = _matches(normalized, _C4_PATTERNS)
    c3_matches = _matches(normalized, _C3_PATTERNS)
    c2_matches = _matches(normalized, _C2_PATTERNS)
    numbered_steps = len(re.findall(r"(?:^|\s)\d+[.)]\s", normalized))
    clause_count = len(re.findall(r"[,;:]|\band\b|\bthen\b", normalized))

    if c4_matches:
        task_class = "C4"
        reason = "high-stakes execution requires an independent critic"
    elif c3_matches:
        task_class = "C3"
        reason = "high-risk domain or irreversible consequence"
    elif c2_matches or len(normalized) >= 700 or numbered_steps >= 3 or clause_count >= 6:
        task_class = "C2"
        reason = "multi-step or medium-complexity reasoning"
    else:
        task_class = "C1"
        reason = "routine, bounded, and reversible"

    return {
        "class": task_class,
        "reason": reason,
        "private": bool(private_matches),
        "features": {
            "high_stakes_matches": len(c4_matches),
            "high_risk_matches": len(c3_matches),
            "complexity_matches": len(c2_matches),
            "private_matches": len(private_matches),
            "numbered_steps": numbered_steps,
            "clause_count": clause_count,
            "character_count": len(message or ""),
        },
    }


def load_policy(path: str | Path) -> dict[str, Any] | None:
    policy_path = Path(path).expanduser()
    if not str(path).strip() or not policy_path.is_file():
        return None
    try:
        with open(policy_path, "r", encoding="utf-8") as handle:
            payload = json.load(handle)
    except (OSError, ValueError):
        logger.warning("Adaptive routing policy is unreadable: %s", policy_path)
        return None
    if payload.get("mode") != "shadow" or not isinstance(payload.get("classes"), dict):
        logger.warning("Adaptive routing policy is not a supported shadow policy: %s", policy_path)
        return None
    return payload


def _runtime_provider(candidate: dict[str, Any] | None) -> str:
    if not candidate:
        return ""
    runtime = candidate.get("runtime") or {}
    return str(runtime.get("provider") or candidate.get("provider") or "")


def decide_shadow_route(
    message: str,
    current_model: str,
    current_provider: str,
    config: dict[str, Any],
) -> dict[str, Any] | None:
    routing = config.get("adaptive_routing") or {}
    if not routing.get("enabled") or str(routing.get("mode") or "shadow") != "shadow":
        return None
    classification = classify_task(message)
    policy = load_policy(str(routing.get("policy_path") or ""))
    class_policy = (
        (policy.get("classes") or {}).get(classification["class"]) if policy else {}
    ) or {}
    recommendation = class_policy.get("shadow_recommendation")
    recommended_provider = _runtime_provider(recommendation)
    blocked_for_privacy = False
    if classification["private"] and recommended_provider:
        allowlist = {
            str(item)
            for item in (routing.get("private_provider_allowlist") or [])
        }
        if recommended_provider not in allowlist:
            recommendation = None
            recommended_provider = ""
            blocked_for_privacy = True

    runtime = (recommendation or {}).get("runtime") or {}
    return {
        "schema_version": 1,
        "mode": "shadow",
        "class": classification["class"],
        "reason": classification["reason"],
        "private": classification["private"],
        "features": classification["features"],
        "current": {
            "provider": current_provider,
            "model": current_model,
        },
        "recommended": (
            {
                "provider": recommended_provider,
                "model": runtime.get("model") or (recommendation or {}).get("model"),
                "worker_mode": runtime.get("mode") or "hermes",
                "critic_provider": _runtime_provider(class_policy.get("critic")),
            }
            if recommendation
            else None
        ),
        "blocked_for_privacy": blocked_for_privacy,
        "promotion_status": class_policy.get("status") or "no_policy",
    }


def _fingerprint(message: str) -> str:
    return hmac.new(
        _PROCESS_FINGERPRINT_KEY,
        str(message or "").encode("utf-8"),
        hashlib.sha256,
    ).hexdigest()[:16]


def record_shadow_decision(
    decision: dict[str, Any],
    message: str,
    telemetry_path: str | Path,
) -> None:
    """Append only non-content routing metadata; failures never break a turn."""
    if not decision:
        return
    path = Path(telemetry_path).expanduser()
    event = dict(decision)
    event["event"] = "route_decision"
    event["created_at"] = datetime.now(timezone.utc).isoformat()
    event["prompt_fingerprint"] = _fingerprint(message)
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        line = json.dumps(event, sort_keys=True, separators=(",", ":")) + "\n"
        with _WRITE_LOCK:
            with open(path, "a", encoding="utf-8") as handle:
                handle.write(line)
    except OSError:
        logger.warning("Could not append adaptive routing telemetry: %s", path)


def observe_shadow_route(
    message: str,
    current_model: str,
    current_provider: str,
    config: dict[str, Any],
) -> dict[str, Any] | None:
    decision = decide_shadow_route(
        message,
        current_model,
        current_provider,
        config,
    )
    if decision:
        routing = config.get("adaptive_routing") or {}
        record_shadow_decision(
            decision,
            message,
            routing.get("telemetry_path")
            or "~/.hermes/logs/adaptive-routing.jsonl",
        )
    return decision
