"""Deterministic shadow and guarded routing for Hermes turns.

This module never invokes a model. It classifies task complexity/risk/privacy
using explicit rules, reads a quality-gated policy generated by the eval
harness, and emits secret-safe JSONL telemetry. ``shadow`` never changes the
runtime. ``guarded`` may select an optimizer-approved native Hermes runtime for
a new session/task epoch; callers must keep that route pinned for the epoch.
"""

from __future__ import annotations

import hashlib
import hmac
import json
import logging
import os
import re
import secrets
import stat
import threading
import time
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from hermes_constants import get_hermes_home
from utils import atomic_json_write


logger = logging.getLogger(__name__)
_PROCESS_FINGERPRINT_KEY = secrets.token_bytes(32)
_WRITE_LOCK = threading.Lock()
_PIN_LOCK = threading.Lock()
_POLICY_ATTESTATION_PRODUCER = (
    "local-ai-router-evals/weekly_router_cycle.py:runtime-policy"
)

try:  # pragma: no cover - Windows does not provide fcntl.
    import fcntl
except ImportError:  # pragma: no cover
    fcntl = None
try:  # pragma: no cover - non-Windows platforms do not provide msvcrt.
    import msvcrt
except ImportError:  # pragma: no cover
    msvcrt = None

_C4_PATTERNS = (
    r"\bdeploy(?:ment)?\b",
    r"\bproduction\b",
    r"\bship\s+(?:it|this|to)\b",
    r"\brollback\b",
    r"\bcanary\b",
    r"\bincident\b",
    r"\bcheckout\b",
    r"\bpayment(?:s)?\b",
    r"\bbilling\b",
    r"\bdelete\s+(?:the\s+)?(?:database|account|records?)\b",
)
_C3_PATTERNS = (
    r"\bsecurity\b",
    r"\bcredential(?:s)?\b",
    r"\bsecret(?:s)?\b",
    r"\bauth(?:entication|orization)?\b",
    r"\blegal\b",
    r"\bmedical\b",
    r"\bfinancial\b",
    r"\btax\b",
    r"\bmigration\b",
    r"\bschema\b",
    r"\binfrastructure\b",
    r"\bdestructive\b",
    r"\bprivacy\b",
    r"\bcompliance\b",
)
_C2_PATTERNS = (
    r"\bplan\b",
    r"\barchitecture\b",
    r"\bimplement\b",
    r"\bdebug\b",
    r"\bcode\b",
    r"\breview\b",
    r"\banaly[sz]e\b",
    r"\bcompare\b",
    r"\bstrategy\b",
    r"\bworkflow\b",
    r"\bmultiple\b",
)
_SECRET_VALUE_PATTERNS = (
    r"\b(?:sk|ghp|github_pat|xox[baprs])[-_][a-z0-9_-]{16,}\b",
    r"\b(?:akia|asia)[a-z0-9]{16}\b",
    r"\baiza[a-z0-9_-]{30,}\b",
    r"\beyj[a-z0-9_-]{10,}\.[a-z0-9_-]{10,}\.[a-z0-9_-]{6,}\b",
    r"(?<![a-z0-9_-])(?=[a-z0-9_-]{32,}(?![a-z0-9_-]))"
    r"(?=[a-z0-9_-]*[a-z])(?=[a-z0-9_-]*\d)[a-z0-9_-]{32,}"
    r"(?![a-z0-9_-])",
)
_PRIVATE_PATTERNS = (
    r"\bprivate\b",
    r"\bpersonal\s+data\b",
    r"\bpii\b",
    r"\b(?:api|access|secret|private)[-_ ]?key\b",
    r"\b(?:password|passcode|recovery\s+code|seed\s+phrase)\b",
    r"\b(?:employee|payroll|personnel)\s+(?:data|record|records|file|files)\b",
    r"\bcustomer\s+(?:data|record|email|phone|address)\b",
    r"\b(?:account|routing|credit\s+card)\s+(?:number|details?)\b",
    r"\bpassport\b",
    r"\b(?:social\s+insurance|social\s+security)\b",
    r"\bhealth\s+record\b",
    r"\bfamily\b",
    r"(?<![\w.+-])[\w.+-]+@[\w-]+(?:\.[\w-]+)+\b",
    r"(?<!\d)(?:\+?1[-.\s]?)?(?:\(?\d{3}\)?[-.\s]?)\d{3}[-.\s]?\d{4}(?!\d)",
    *_SECRET_VALUE_PATTERNS,
)


def _matches(text: str, patterns: tuple[str, ...]) -> list[str]:
    return [pattern for pattern in patterns if re.search(pattern, text)]


def _policy_attestation_valid(payload: dict[str, Any]) -> bool:
    attestation = payload.get("evidence_attestation")
    if (
        not isinstance(attestation, dict)
        or attestation.get("schema_version") != 1
        or attestation.get("algorithm") != "hmac-sha256"
        or attestation.get("producer") != _POLICY_ATTESTATION_PRODUCER
        or not isinstance(attestation.get("signature"), str)
    ):
        return False
    key_path = Path(
        os.environ.get("HERMES_ROUTER_EVIDENCE_KEY_PATH")
        or "~/.hermes/state/model-router/evidence-signing.key"
    ).expanduser()
    try:
        metadata = key_path.stat()
        if metadata.st_mode & (stat.S_IRWXG | stat.S_IRWXO):
            return False
        key = key_path.read_bytes()
    except OSError:
        return False
    if len(key) < 32:
        return False
    unsigned = dict(payload)
    unsigned.pop("evidence_attestation", None)
    canonical = json.dumps(
        unsigned,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    domain = (
        "hermes-router-evidence-v1\0hmac-sha256\0"
        f"{_POLICY_ATTESTATION_PRODUCER}\0"
    ).encode("utf-8")
    expected = hmac.new(key, domain + canonical, hashlib.sha256).hexdigest()
    return hmac.compare_digest(attestation["signature"], expected)


def classify_task(
    message: str,
    *,
    assume_private: bool = False,
) -> dict[str, Any]:
    """Return a deterministic C1-C4 classification without retaining content."""
    normalized = " ".join(str(message or "").lower().split())
    private_matches = _matches(normalized, _PRIVATE_PATTERNS)
    if assume_private:
        private_matches.append("uninspected_attachment")
    c4_matches = _matches(normalized, _C4_PATTERNS)
    c3_matches = _matches(normalized, _C3_PATTERNS)
    c3_matches.extend(_matches(normalized, _SECRET_VALUE_PATTERNS))
    c2_matches = _matches(normalized, _C2_PATTERNS)
    numbered_steps = len(re.findall(r"(?:^|\s)\d+[.)]\s", normalized))
    clause_count = len(re.findall(r"[,;:]|\band\b|\bthen\b", normalized))

    if c4_matches:
        task_class = "C4"
        reason = "high-stakes execution requires an independent critic"
    elif c3_matches:
        task_class = "C3"
        reason = "high-risk domain or irreversible consequence"
    elif c2_matches or len(normalized) >= 700 or numbered_steps >= 3 or clause_count >= 6:
        task_class = "C2"
        reason = "multi-step or medium-complexity reasoning"
    else:
        task_class = "C1"
        reason = "routine, bounded, and reversible"

    return {
        "class": task_class,
        "reason": reason,
        "private": bool(private_matches),
        "features": {
            "high_stakes_matches": len(c4_matches),
            "high_risk_matches": len(c3_matches),
            "complexity_matches": len(c2_matches),
            "private_matches": len(private_matches),
            "numbered_steps": numbered_steps,
            "clause_count": clause_count,
            "character_count": len(message or ""),
        },
    }


def load_policy(
    path: str | Path,
    *,
    maximum_age_seconds: int | None = None,
    now: float | None = None,
) -> dict[str, Any] | None:
    policy_path = Path(path).expanduser()
    if not str(path).strip() or not policy_path.is_file():
        return None
    try:
        with open(policy_path, "r", encoding="utf-8") as handle:
            payload = json.load(handle)
    except (OSError, ValueError):
        logger.warning("Adaptive routing policy is unreadable: %s", policy_path)
        return None
    if (
        not isinstance(payload, dict)
        or payload.get("mode") != "shadow"
        or not isinstance(payload.get("classes"), dict)
    ):
        logger.warning("Adaptive routing policy is not a supported shadow policy: %s", policy_path)
        return None
    if maximum_age_seconds is not None:
        if not _policy_attestation_valid(payload):
            logger.warning(
                "Guarded routing policy has no valid runtime-policy attestation"
            )
            return None
        generated = payload.get("generated_at") or payload.get("created_at")
        try:
            generated_at = datetime.fromisoformat(
                str(generated).replace("Z", "+00:00")
            )
            if generated_at.tzinfo is None:
                generated_at = generated_at.replace(tzinfo=timezone.utc)
            age = (time.time() if now is None else now) - generated_at.timestamp()
        except (TypeError, ValueError):
            logger.warning("Guarded routing policy has no valid generation time")
            return None
        if age < -300 or age > max(60, int(maximum_age_seconds)):
            logger.warning("Guarded routing policy is stale or future-dated")
            return None
    return payload


def _runtime_provider(candidate: dict[str, Any] | None) -> str:
    if not candidate:
        return ""
    runtime = candidate.get("runtime") or {}
    return str(runtime.get("provider") or candidate.get("provider") or "")


def _pin_path(config: dict[str, Any]) -> Path:
    routing = config.get("adaptive_routing") or {}
    configured = str(routing.get("pin_path") or "").strip()
    if configured:
        return Path(os.path.expandvars(configured)).expanduser()
    return get_hermes_home() / "state" / "adaptive-route-pins.json"


def _pin_id(pin_key: str) -> str:
    return hashlib.sha256(str(pin_key or "").encode("utf-8")).hexdigest()


def _load_pins(path: Path) -> dict[str, Any] | None:
    try:
        with open(path, encoding="utf-8") as handle:
            payload = json.load(handle)
    except FileNotFoundError:
        return {"schema_version": 1, "pins": {}}
    except (OSError, ValueError):
        logger.warning("Adaptive route pin state is unreadable; preserving it: %s", path)
        return None
    if payload.get("schema_version") != 1 or not isinstance(payload.get("pins"), dict):
        logger.warning("Adaptive route pin state has an unsupported schema: %s", path)
        return None
    return payload


@contextmanager
def _pin_file_lock(path: Path):
    lock_path = path.with_suffix(path.suffix + ".lock")
    lock_path.parent.mkdir(parents=True, exist_ok=True)
    with _PIN_LOCK:
        with open(lock_path, "a+b") as handle:
            if msvcrt is not None:
                handle.seek(0, os.SEEK_END)
                if handle.tell() == 0:
                    handle.write(b"\0")
                    handle.flush()
                handle.seek(0)
                msvcrt.locking(handle.fileno(), msvcrt.LK_LOCK, 1)
            if fcntl is not None:
                fcntl.flock(handle.fileno(), fcntl.LOCK_EX)
            try:
                yield
            finally:
                if fcntl is not None:
                    fcntl.flock(handle.fileno(), fcntl.LOCK_UN)
                if msvcrt is not None:
                    handle.seek(0)
                    msvcrt.locking(handle.fileno(), msvcrt.LK_UNLCK, 1)


def get_route_pin(pin_key: str, config: dict[str, Any]) -> dict[str, Any] | None:
    if not str(pin_key or "").strip():
        return None
    path = _pin_path(config)
    with _pin_file_lock(path):
        payload = _load_pins(path)
    if payload is None:
        raise RuntimeError("adaptive route pin state is unavailable")
    entry = payload["pins"].get(_pin_id(pin_key))
    if not isinstance(entry, dict):
        return None
    provider = str(entry.get("provider") or "").strip()
    model = str(entry.get("model") or "").strip()
    if not provider or not model:
        return None
    return {
        "provider": provider,
        "model": model,
        "worker_mode": "hermes",
        "critic_provider": str(entry.get("critic_provider") or ""),
        "task_class": str(entry.get("task_class") or "C1"),
        "private": bool(entry.get("private")),
    }


def _save_route_pin(
    pin_key: str,
    active: dict[str, Any],
    config: dict[str, Any],
) -> bool:
    if not str(pin_key or "").strip():
        return False
    path = _pin_path(config)
    with _pin_file_lock(path):
        payload = _load_pins(path)
        if payload is None:
            return False
        payload["pins"][_pin_id(pin_key)] = {
            "provider": str(active.get("provider") or ""),
            "model": str(active.get("model") or ""),
            "critic_provider": str(active.get("critic_provider") or ""),
            "task_class": str(active.get("task_class") or "C1"),
            "private": bool(active.get("private")),
            "selected_at": datetime.now(timezone.utc).isoformat(),
        }
        maximum = max(
            16,
            int(
                (config.get("adaptive_routing") or {}).get("maximum_session_pins")
                or 1024
            ),
        )
        if len(payload["pins"]) > maximum:
            ordered = sorted(
                payload["pins"].items(),
                key=lambda item: str((item[1] or {}).get("selected_at") or ""),
                reverse=True,
            )
            payload["pins"] = dict(ordered[:maximum])
        payload["updated_at"] = datetime.now(timezone.utc).isoformat()
        path.parent.mkdir(parents=True, exist_ok=True)
        atomic_json_write(path, payload)
        return True


def decide_shadow_route(
    message: str,
    current_model: str,
    current_provider: str,
    config: dict[str, Any],
) -> dict[str, Any] | None:
    """Compatibility wrapper for callers/tests that explicitly want shadow."""
    shadow_config = dict(config)
    routing = dict(config.get("adaptive_routing") or {})
    routing["mode"] = "shadow"
    shadow_config["adaptive_routing"] = routing
    return decide_route(
        message,
        current_model,
        current_provider,
        shadow_config,
    )


def decide_route(
    message: str,
    current_model: str,
    current_provider: str,
    config: dict[str, Any],
    *,
    assume_private: bool = False,
) -> dict[str, Any] | None:
    routing = config.get("adaptive_routing") or {}
    mode = str(routing.get("mode") or "shadow").strip().lower()
    if not routing.get("enabled") or mode not in {"shadow", "guarded"}:
        return None
    classification = classify_task(message, assume_private=assume_private)
    policy = load_policy(
        str(routing.get("policy_path") or ""),
        maximum_age_seconds=(
            int(routing.get("maximum_policy_age_seconds") or 172800)
            if mode == "guarded"
            else None
        ),
    )
    class_policy = (
        (policy.get("classes") or {}).get(classification["class"]) if policy else {}
    ) or {}
    recommendation = class_policy.get("shadow_recommendation")
    recommended_provider = _runtime_provider(recommendation)
    blocked_for_privacy = False
    if classification["private"] and recommended_provider:
        allowlist = {
            str(item)
            for item in (routing.get("private_provider_allowlist") or [])
        }
        if recommended_provider not in allowlist:
            recommendation = None
            recommended_provider = ""
            blocked_for_privacy = True

    selected = class_policy.get("selected") if mode == "guarded" else None
    selected_provider = _runtime_provider(selected)
    selected_runtime = (selected or {}).get("runtime") or {}
    activation_blockers: list[str] = []
    block_execution = False
    if mode == "guarded":
        if not selected:
            activation_blockers.append("no promotion-eligible selected route")
        elif str(class_policy.get("status") or "") != "candidate":
            activation_blockers.append(
                "selected route is not in promotion-candidate status"
            )
        elif str(selected_runtime.get("mode") or "") != "hermes":
            activation_blockers.append("selected route is not a native Hermes runtime")
        elif classification["private"]:
            allowlist = {
                str(item)
                for item in (routing.get("private_provider_allowlist") or [])
            }
            if selected_provider not in allowlist:
                activation_blockers.append(
                    "selected route violates private-provider allowlist"
                )
        if classification["class"] == "C4":
            critic = class_policy.get("critic") or {}
            critic_provider = _runtime_provider(critic)
            critic_runtime = critic.get("runtime") or {}
            critic_model = str(
                critic_runtime.get("model") or critic.get("model") or ""
            )
            if not critic_provider or critic_provider == selected_provider:
                activation_blockers.append(
                    "C4 requires a different-provider critic"
                )
            elif (
                (config.get("provider_circuits") or {}).get("enabled", True)
                and critic_model
            ):
                try:
                    from hermes_cli.provider_circuits import (
                        circuit_status,
                        state_path,
                    )

                    critic_status = circuit_status(
                        critic_provider,
                        critic_model,
                        path=state_path(config),
                    )
                    if critic_status["status"] == "open":
                        activation_blockers.append(
                            "C4 critic has an open provider circuit"
                        )
                    elif critic_status["status"] == "unavailable":
                        activation_blockers.append(
                            "C4 critic circuit state is unavailable"
                        )
                except Exception:
                    activation_blockers.append(
                        "C4 critic circuit state is unavailable"
                    )
            # This route resolver cannot execute and verify a second model.
            # Never imply that merely naming a critic satisfied the C4 gate.
            activation_blockers.append(
                "C4 independent critic execution is not available in this runtime path"
            )
            block_execution = True
        if (
            classification["private"]
            and (not selected or bool(activation_blockers))
            and current_provider
            not in {
                str(item)
                for item in (routing.get("private_provider_allowlist") or [])
            }
        ):
            activation_blockers.append(
                "configured primary violates private-provider allowlist"
            )
            block_execution = True

    runtime = (recommendation or {}).get("runtime") or {}
    return {
        "schema_version": 1,
        "mode": mode,
        "class": classification["class"],
        "reason": classification["reason"],
        "private": classification["private"],
        "allowed_fallback_providers": (
            sorted(
                {
                    str(item)
                    for item in (routing.get("private_provider_allowlist") or [])
                }
            )
            if classification["private"]
            else None
        ),
        "features": classification["features"],
        "current": {
            "provider": current_provider,
            "model": current_model,
        },
        "recommended": (
            {
                "provider": recommended_provider,
                "model": runtime.get("model") or (recommendation or {}).get("model"),
                "worker_mode": runtime.get("mode") or "hermes",
                "critic_provider": _runtime_provider(class_policy.get("critic")),
            }
            if recommendation
            else None
        ),
        "blocked_for_privacy": blocked_for_privacy,
        "promotion_status": class_policy.get("status") or "no_policy",
        "active": (
            {
                "provider": selected_provider,
                "model": selected_runtime.get("model") or (selected or {}).get("model"),
                "worker_mode": selected_runtime.get("mode") or "hermes",
                "critic_provider": _runtime_provider(class_policy.get("critic")),
            }
            if selected and not activation_blockers
            else None
        ),
        "activation_blockers": activation_blockers,
        "block_execution": block_execution,
    }


def apply_guarded_route(
    route: dict[str, Any],
    decision: dict[str, Any] | None,
    config: dict[str, Any],
    *,
    resolve_runtime=None,
    pin_key: str | None = None,
) -> dict[str, Any]:
    """Resolve an approved route, otherwise retain the configured primary."""
    if not decision or decision.get("mode") != "guarded":
        return route

    def block_unsafe_private_primary(reason: str) -> None:
        """Prevent a guarded failure from reverting private work to cloud."""
        if not decision.get("private"):
            return
        allowlist = {
            str(item)
            for item in (
                (config.get("adaptive_routing") or {}).get(
                    "private_provider_allowlist"
                )
                or []
            )
        }
        configured_provider = str(
            (route.get("runtime") or {}).get("provider") or ""
        )
        if configured_provider not in allowlist:
            decision["block_execution"] = True
            decision["activation_blockers"].append(reason)

    pinned = get_route_pin(pin_key or "", config) if pin_key else None
    active = pinned or decision.get("active") or {}
    if pinned:
        class_rank = {"C1": 1, "C2": 2, "C3": 3, "C4": 4}
        current_class = str(decision.get("class") or "C1")
        prior_class = str(pinned.get("task_class") or "C1")
        epoch_class = max(
            (prior_class, current_class),
            key=lambda value: class_rank.get(value, 4),
        )
        epoch_private = bool(pinned.get("private") or decision.get("private"))
        pinned["task_class"] = epoch_class
        pinned["private"] = epoch_private
        # Risk/privacy only escalate within a pinned task epoch. Mirror the
        # accumulated values back onto the decision so downstream primary
        # fallback and fallback-chain filtering cannot use the lower-risk
        # classification from a later short follow-up.
        decision["class"] = epoch_class
        decision["private"] = epoch_private
        if epoch_class == "C4":
            decision["block_execution"] = True
            decision["activation_blockers"].append(
                "pinned task epoch escalated to C4 and requires an independent critic"
            )
        allowlist = {
            str(item)
            for item in (
                (config.get("adaptive_routing") or {}).get(
                    "private_provider_allowlist"
                )
                or []
            )
        }
        if epoch_private and str(pinned.get("provider") or "") not in allowlist:
            decision["block_execution"] = True
            decision["activation_blockers"].append(
                "pinned task epoch violates private-provider allowlist"
            )
        decision["allowed_fallback_providers"] = (
            sorted(allowlist) if epoch_private else None
        )
        if not _save_route_pin(pin_key or "", pinned, config):
            decision["block_execution"] = True
            decision["activation_blockers"].append(
                "updated task route pin could not be persisted"
            )
        decision["active"] = pinned
        decision["pinned"] = True
    if decision.get("block_execution"):
        decision["active"] = None
        return route
    provider = str(active.get("provider") or "").strip()
    model = str(active.get("model") or "").strip()
    if not provider or not model:
        block_unsafe_private_primary(
            "guarded route is unavailable and configured primary violates "
            "private-provider allowlist"
        )
        return route
    try:
        from hermes_cli.provider_circuits import circuit_status, state_path

        if (config.get("provider_circuits") or {}).get("enabled", True):
            status = circuit_status(
                provider,
                model,
                path=state_path(config),
            )
            if status["status"] == "open":
                decision["activation_blockers"].append(
                    (
                        "pinned route has an open provider circuit"
                        if pinned
                        else "selected route has an open provider circuit"
                    )
                )
                decision["active"] = None
                block_unsafe_private_primary(
                    "guarded route circuit is open and configured primary "
                    "violates private-provider allowlist"
                )
                return route
            if status["status"] == "unavailable":
                decision["activation_blockers"].append(
                    "provider circuit state unavailable"
                )
                decision["active"] = None
                block_unsafe_private_primary(
                    "guarded circuit state is unavailable and configured "
                    "primary violates private-provider allowlist"
                )
                return route
    except Exception:
        logger.debug("Guarded route circuit check failed", exc_info=True)
        decision["activation_blockers"].append("provider circuit state unavailable")
        decision["active"] = None
        block_unsafe_private_primary(
            "guarded circuit check failed and configured primary violates "
            "private-provider allowlist"
        )
        return route

    if (
        provider == str((route.get("runtime") or {}).get("provider") or "")
        and model == str(route.get("model") or "")
    ):
        if not pinned and pin_key:
            pin = {
                **active,
                "task_class": decision.get("class") or "C1",
                "private": bool(decision.get("private")),
            }
            decision["pinned"] = _save_route_pin(pin_key, pin, config)
            if not decision["pinned"]:
                decision["block_execution"] = True
                decision["active"] = None
                decision["activation_blockers"].append(
                    "task route pin could not be persisted"
                )
        return route

    try:
        if resolve_runtime is None:
            from hermes_cli.runtime_provider import resolve_runtime_provider

            resolve_runtime = resolve_runtime_provider
        resolved = resolve_runtime(requested=provider, target_model=model)
        runtime = {
            "api_key": resolved.get("api_key"),
            "base_url": resolved.get("base_url"),
            "provider": str(resolved.get("provider") or provider),
            # Keep the policy/provider identity distinct from generic
            # transports such as "custom" so persistent circuits and the
            # daily control plane use the same stable key.
            "circuit_provider": provider,
            "api_mode": resolved.get("api_mode"),
            "command": None,
            "args": [],
            "credential_pool": resolved.get("credential_pool"),
            "max_tokens": (route.get("runtime") or {}).get("max_tokens"),
        }
        guarded = dict(route)
        guarded["model"] = model
        guarded["runtime"] = runtime
        guarded["signature"] = (
            model,
            runtime["provider"],
            runtime["base_url"],
            runtime["api_mode"],
            runtime["command"],
            tuple(runtime["args"]),
        )
        guarded["adaptive_routing"] = decision
        if not pinned and pin_key:
            pin = {
                **active,
                "task_class": decision.get("class") or "C1",
                "private": bool(decision.get("private")),
            }
            decision["pinned"] = _save_route_pin(pin_key, pin, config)
            if not decision["pinned"]:
                decision["block_execution"] = True
                decision["active"] = None
                decision["activation_blockers"].append(
                    "task route pin could not be persisted"
                )
                return route
        return guarded
    except Exception:
        logger.warning(
            "Guarded route resolution failed for %s/%s; retaining configured primary",
            provider,
            model,
        )
        decision["activation_blockers"].append("selected runtime could not be resolved")
        decision["active"] = None
        block_unsafe_private_primary(
            "guarded route resolution failed and configured primary violates "
            "private-provider allowlist"
        )
        return route


def filter_fallbacks_for_decision(
    fallback_model: Any,
    decision: dict[str, Any] | None,
) -> Any:
    """Remove providers that are ineligible for a private task epoch."""
    allowed_values = (decision or {}).get("allowed_fallback_providers")
    if allowed_values is None:
        return fallback_model
    allowed = {str(item) for item in allowed_values}
    if isinstance(fallback_model, list):
        return [
            item
            for item in fallback_model
            if isinstance(item, dict)
            and str(item.get("provider") or "") in allowed
        ]
    if isinstance(fallback_model, dict):
        return (
            fallback_model
            if str(fallback_model.get("provider") or "") in allowed
            else []
        )
    return []


def _fingerprint(message: str) -> str:
    return hmac.new(
        _PROCESS_FINGERPRINT_KEY,
        str(message or "").encode("utf-8"),
        hashlib.sha256,
    ).hexdigest()[:16]


def record_shadow_decision(
    decision: dict[str, Any],
    message: str,
    telemetry_path: str | Path,
) -> None:
    """Append only non-content routing metadata; failures never break a turn."""
    if not decision:
        return
    path = Path(telemetry_path).expanduser()
    event = dict(decision)
    event["event"] = "route_decision"
    event["created_at"] = datetime.now(timezone.utc).isoformat()
    event["prompt_fingerprint"] = _fingerprint(message)
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        line = json.dumps(event, sort_keys=True, separators=(",", ":")) + "\n"
        with _WRITE_LOCK:
            with open(path, "a", encoding="utf-8") as handle:
                handle.write(line)
    except OSError:
        logger.warning("Could not append adaptive routing telemetry: %s", path)


def observe_shadow_route(
    message: str,
    current_model: str,
    current_provider: str,
    config: dict[str, Any],
    *,
    assume_private: bool = False,
) -> dict[str, Any] | None:
    decision = decide_route(
        message,
        current_model,
        current_provider,
        config,
        assume_private=assume_private,
    )
    if decision:
        routing = config.get("adaptive_routing") or {}
        record_shadow_decision(
            decision,
            message,
            routing.get("telemetry_path")
            or "~/.hermes/logs/adaptive-routing.jsonl",
        )
    return decision
